### ISSUE TITLE
code for the models

### ISSUE THREAD

**Issue by alvespedros** [shoaib-intro/logs_Analysis#2]
Hey, how are you doing?

I have been working with the log key anomaly detection model of deep log and I also would like to use the parameter value anomaly detection model. Could you share the code for the model that you use in these notebooks?

Thanks in advance

**Comment by shoaib-intro** [comment]
Hi sorry for late reply, 

please find parameters anomaly detection model code in `matrix.py` file. its old file do let me know if you encounter any problems.
